baseURL = ""
languageCode = "en-us"
title = "Fries Consulting Services, LLC."
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Your one-stop IT consulting service."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/davidfries"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 2